User/urls.py
from django.urls import path, include
from . import views

app_name = 'User'
urlpatterns = [
    # Basic function
    path('', include([
        path('', views.login, name='login'),
        path('register/', views.register, name='register'),
        path('logout/', views.logout_user, name='logout'),
        path('profile/', views.profile, name='profile'),
        path('delete/',views.delete_profile, name='delete'),
    ]))
]

WebDjango/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #    path("admin/", admin.site.urls),
    path('', include('User.urls', namespace='user')),
]

User/models.py
from django.db import models

# Create your models here.

User/views.py
from django.contrib import messages, auth
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from . import utils


# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect('user:profile')

    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']

        context = {
            'username': username,
            'email': email,
            'first_name': first_name,
            'last_name': last_name
        }

        if not (7 <= len(username) <= 30):
            messages.error(request, 'Username must be between 7 and 20 characters')
            return redirect('user:register')

        if not utils.check_password_case(password1):
            messages.error(request, 'Password must contain both uppercase and lowercase letters')
            return redirect('user:register')

        if not utils.check_password_case(password2):
            messages.error(request, 'Password must contain both uppercase and lowercase letters')
            return redirect('user:register')

        if not utils.check_password_numeric_and_symbols(password1):
            messages.error(request, 'Password must contain numeric and special characters')
            return redirect('user:register')

        if not utils.check_password_numeric_and_symbols(password2):
            messages.error(request, 'Password must contain numeric and special characters')
            return redirect('user:register')

        try:
            validate_password(password1)
        except ValidationError as e:
            messages.error(request, ', '.join(e.messages))
            return redirect('user:register')

        if User.objects.filter(username=username).exists():
            messages.error(request, 'Username already exists, choose another one')
            return redirect('user:register')

        if User.objects.filter(email=email).exists():
            messages.error(request, 'Email already exists, choose another one')
            return redirect('user:register')

        if password1 == password2:
            try:
                User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                         email=email, password=password1)
                messages.success(request, "Registration Successful. Please login to continue.")
                return redirect('user:login')
            except ValidationError as e:
                messages.error(request, ', '.join(e.messages))
                return redirect('user:register')
        else:
            messages.error(request, 'Passwords do not match')
            return redirect('user:register')
    else:
        return render(request, 'Register.html', context)


def login(request):
    if request.user.is_authenticated:
        return redirect('user:profile')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        context = {
            'username': username,
        }

        try:
            user_auth = auth.authenticate(request=request, username=username, password=password)

            if user_auth is not None:
                auth.login(request, user_auth)
                messages.success(request, 'You have successfully logged in.')
                return redirect('user:profile')
            else:
                messages.error(request, 'Invalid username or password.')
                return render(request, 'Login.html', context)

        except User.DoesNotExist:
            messages.error(request, 'Invalid username or password.')
            render(request, 'Login.html', context)

    return render(request, 'Login.html')


def logout_user(request):
    logout(request)
    messages.success(request, "You have been successfully logged out.")
    return redirect('user:login')


@login_required
def profile(request):
    if not request.user.is_authenticated:
        return redirect('user:login')
    if request.method == 'POST':
        username1 = request.POST['username']
        email1 = request.POST['email']

        try:
            user = User.objects.get(username=request.user.username)
            user.username = username1
            user.email = email1
            user.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('user:profile')
        except Exception as e:
            messages.error(request, f'An error occurred: {str(e)}')
            return redirect('user:profile')
    return render(request, 'Profile.html')


def delete_profile(request):
    if not request.user.is_authenticated:
        return redirect('user:login')
    try:
        user = User.objects.get(username=request.user.username)
        user.delete()
        messages.success(request, 'Profile deleted successfully.')
        return redirect('user:login')
    except Exception as e:
        messages.error(request, f'An error occurred: {str(e)}')
        return redirect('user:profile')

templates/Base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    {% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body class="w-full min-h-screen m-0 p-0 text-white">
{% block body %}
{% endblock %}
<div class="fixed top-[20px] left-1/2 transform -translate-x-1/2 z-50">
    {% for message in messages %}
        <div class="alert w-[400px] p-4 mb-4 text-sm rounded-lg {{ message.tags }}"
        >
            {{ message | safe }}
        </div>
    {% endfor %}
</div>
<footer class="w-full text-center p-4 bg-black text-white">
    <p>Use Django and tailwind to do</p>
</footer>
{% block script %}
{% endblock %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var alerts = document.querySelectorAll('.alert');
        alerts.forEach(function (alert) {
            setTimeout(function () {
                alert.style.opacity = '0';
                alert.style.transform = 'translateY(-20px)';

                setTimeout(function () {
                    alert.remove();
                }, 500);
            }, 3000);
        });
    });
</script>
</body>
</html>

templates/Login.html
{% extends "Base.html" %}
{% block title %}Login{% endblock %}
{% block body %}
    <div class="w-full min-h-screen bg-black flex flex-col">
        <div class="flex-1 flex items-center justify-center">
            <div class="flex flex-col items-center justify-center border rounded-xl w-[400px] p-6 bg-gray-800 backdrop-blur-2xl">
                <form method="POST" class="w-full">
                    {% csrf_token %}
                    <div class=" mb-[10px] text-center">
                        <h2>Login</h2>
                    </div>

                    <div class="relative mb-[10px]">
                        <input type="text" id="RegisterUsername" name="username"
                               class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                               value="{{ username|default:'' }}" placeholder=" "
                               required>
                        <label for="RegisterUsername"
                               class="absolute hover:bg-transparent bg-transparent text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto start-1">Username</label>
                    </div>

                    <div class="relative mb-[10px]">
                        <input type="password" id="RegisterPassword" name="password"
                               class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                               placeholder=" "
                               required>
                        <label for="RegisterPassword"
                               class="absolute hover:bg-transparent bg-transparent text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto start-1">Password</label>
                    </div>

                    <div class="relative mb-[10px] w-full">
                        <button class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 w-full">
<span class="relative w-full px-5 py-2.5 transition-all ease-in duration-75 bg-transparent dark:bg-gray-900 rounded-md group-hover:bg-transparent group-hover:dark:bg-transparent">
Login
</span></button>
                    </div>

                    <div class="">
                        <p>Don't have an account? <a href="{% url 'user:register' %}"
                                                     class="text-sky-300 dark:text-sky-300 underline decoration-sky-300">Register
                            here</a></p>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/Profile.html
{% extends "Base.html" %}
{% block title %}Profile{% endblock %}
{% block body %}
    <div class="w-full min-h-screen bg-black flex flex-col">
        <div class="flex-1 flex items-center justify-center">
            <div class="flex flex-col  items-center justify-center border rounded-xl w-[400px] p-6 bg-gray-800 backdrop-blur-2xl">
                <div class="grid mb-[10px] grid-cols-3 content-between gap-4">
                    <h2 class="font-normal place-content-start">Profile </h2>
                    <div id="UpdateInput" class="col-start-3 col-end-4 text-end place-content-end">
                        <button onclick="Change()"
                                class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-cyan-200 dark:focus:ring-cyan-800">
<span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-transparent group-hover:dark:bg-transparent">
Update
</span>
                        </button>
                    </div>
                </div>
                <form method="POST" class="w-full">
                    {% csrf_token %}
                    <div class="mb-[10px] w-full">
                        <p class="text-gray-300 block" id="username"><strong>Username:</strong> {{ user.username }}</p>
                        <div class="hidden relative " id="divUsernameInput">
                            <input id="usernameInput" type="text" name="username"
                                   class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                                   placeholder=" "/>
                            <label class="absolute hover:bg-transparent bg-transparent text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto start-1"
                                   for="usernameInput">{{ user.username }}</label>
                        </div>
                    </div>

                    <div class="mb-[10px] w-full">
                        <p class="text-gray-300 block" id="email"><strong>Email:</strong> {{ user.email }}</p>
                        <div id="divEmailInput" class="hidden relative">
                            <input id="emailInput" type="email" name="email"
                                   class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                                   placeholder=" "/>
                            <label class="absolute hover:bg-transparent bg-transparent text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto start-1"
                                   for="emailInput">{{ user.email }}</label>
                        </div>
                    </div>

                    <div id="updateProfile" class="hidden relative mb-[10px] w-full">
                        <button type="submit"
                                class="w-full relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-cyan-200 dark:focus:ring-cyan-800">
<span class="w-full relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-transparent group-hover:dark:bg-transparent">
Update Profile
</span>
                        </button>
                    </div>
                </form>
                <div id="cancelUpdate" class="hidden relative mb-[10px] w-full">
                    <button onclick="Cancel()"
                            class="w-full relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-cyan-200 dark:focus:ring-cyan-800">
<span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-transparent group-hover:dark:bg-transparent w-full">
Cancel
</span>
                    </button>
                </div>
                <div id="logout" class="relative mb-[10px] w-full">
                    <a href="{% url 'user:logout' %}"
                       class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 w-full">
                        <span class="relative w-full px-5 py-2.5 transition-all ease-in duration-75 bg-transparent dark:bg-gray-900 rounded-md group-hover:bg-transparent group-hover:dark:bg-transparent">
                            Logout
                        </span>
                    </a>
                </div>
                <div id="delete" class="relative mb-[10px] w-full">
                    <a href="{% url 'user:delete' %}"
                       class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 w-full">
                        <span class="relative w-full px-5 py-2.5 transition-all ease-in duration-75 bg-transparent dark:bg-gray-900 rounded-md group-hover:bg-transparent group-hover:dark:bg-transparent">
                            Delete Account
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        function Change() {
            const username1 = document.getElementById('username');
            const usernameInput = document.getElementById('divUsernameInput');
            const email1 = document.getElementById('email');
            const emailInput = document.getElementById('divEmailInput');
            const UpdateProfile = document.getElementById('updateProfile');
            const updateInput = document.getElementById('UpdateInput');
            const logout = document.getElementById('logout');
            const cancelUpdate = document.getElementById('cancelUpdate');
            const delete_use = document.getElementById('delete');
            if (usernameInput.classList.contains('hidden')) {
                username1.classList.add('hidden');
                usernameInput.classList.remove('hidden');
                email1.classList.add('hidden');
                emailInput.classList.remove('hidden');
                UpdateProfile.classList.remove('hidden');
                updateInput.classList.add('hidden');
                logout.classList.add('hidden');
                delete_use.classList.add('hidden');
                cancelUpdate.classList.remove('hidden');
            }
        }

        function Cancel() {
            const username1 = document.getElementById('username');
            const usernameInput = document.getElementById('divUsernameInput');
            const email1 = document.getElementById('email');
            const emailInput = document.getElementById('divEmailInput');
            const UpdateProfile = document.getElementById('updateProfile');
            const updateInput = document.getElementById('UpdateInput');
            const logout = document.getElementById('logout');
            const cancelUpdate = document.getElementById('cancelUpdate');
            const delete_use = document.getElementById('delete');
            if (!usernameInput.classList.contains('hidden')) {
                username1.classList.remove('hidden');
                usernameInput.classList.add('hidden');
                email1.classList.remove('hidden');
                emailInput.classList.add('hidden');
                UpdateProfile.classList.add('hidden');
                updateInput.classList.remove('hidden');
                logout.classList.remove('hidden');
                delete_use.classList.remove('hidden');
                cancelUpdate.classList.add('hidden');
            }
        }

    </script>
{% endblock %}

templates/Register.html
{% extends "Base.html" %}
{% block title %}
    Register Page
{% endblock %}

{% block body %}
    <div class="w-full min-h-screen bg-black flex flex-col">
        <div class="flex-1 flex items-center justify-center">
            <div class="flex flex-col items-center justify-center border rounded-xl w-[400px] p-6 bg-gray-800 backdrop-blur-2xl">
                <form method="POST" class="w-full">
                    {% csrf_token %}
                    <div class=" mb-[10px] text-center">
                        <h1>Sign Up</h1>
                        <p>Create your account to get started</p>
                    </div>

                    <div class="relative mb-[10px]">
                        <input type="text" id="RegisterUsername" name="username"
                               class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                               value="{{ username|default:'' }}" placeholder=" "
                               required>
                        <label for="RegisterUsername"
                               class="absolute hover:bg-transparent bg-transparent text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto start-1">Username</label>
                    </div>

                    <div class="relative mb-[10px]">
                        <input type="password" id="RegisterPassword" name="password1"
                               class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                               placeholder=" "
                               required>
                        <label for="RegisterPassword"
                               class="absolute hover:bg-transparent bg-transparent text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto start-1">Password</label>
                    </div>

                    <div class="relative mb-[10px]">
                        <input type="password" id="RegisterConfirmPassword" name="password2"
                               class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                               placeholder=" "
                               required>
                        <label for="RegisterConfirmPassword"
                               class="absolute hover:bg-transparent bg-transparent text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto start-1">
                            Confirm Password</label>
                    </div>

                    <div class="relative mb-[10px]">
                        <input type="email" id="RegisterEmail" name="email"
                               class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                               value="{{ email|default:'' }}" placeholder=" "
                               required>
                        <label for="RegisterEmail"
                               class="absolute hover:bg-transparent bg-transparent text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto start-1">Email</label>
                    </div>

                    <div class="relative mb-[10px]">
                        <input type="text" id="RegisterFirst" name="first_name"
                               class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                               value="{{ first_name|default:'' }}" placeholder=" "
                               required>
                        <label for="RegisterFirst"
                               class="absolute hover:bg-transparent bg-transparent text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto start-1">First
                            Name</label>
                    </div>

                    <div class="relative mb-[10px]">
                        <input type="text" id="RegisteredLast" name="last_name"
                               class="block px-2.5 pb-2.5 pt-4 w-full text-sm text-gray-900 bg-transparent rounded-lg border-1 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                               value="{{ last_name|default:'' }}" placeholder=" "
                               required>
                        <label for="RegisteredLast"
                               class="absolute hover:bg-transparent bg-transparent text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] px-2 peer-focus:px-2 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-2 peer-focus:scale-75 peer-focus:-translate-y-4 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto start-1">Last
                            Name</label>
                    </div>
                    <div class="relative mb-[10px] w-full">
                        <button class="relative inline-flex items-center justify-center p-0.5 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 w-full">
<span class="relative w-full px-5 py-2.5 transition-all ease-in duration-75 bg-transparent dark:bg-gray-900 rounded-md group-hover:bg-transparent group-hover:dark:bg-transparent">
Register
</span></button>
                    </div>

                    <div class="">
                        <p>Already have an account? <a href="{% url 'user:login' %}" class="text-sky-300 dark:text-sky-300 underline decoration-sky-300">Login here</a>
                        </p>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}